common/urls.py
from django.urls import path
from rooms import views as room_views


app_name = 'common'

urlpatterns = [
    path('', room_views.HomeView.as_view(), name='home'),
]

lists/urls.py
from django.urls import path
from . import views


app_name = 'lists'

urlpatterns = [
    path('toggle/<int:room_pk>', views.toggle_room, name='toggle-room'),
    path('favs/', views.SeeFavouritesView.as_view(), name='see-favs'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('common.urls', namespace='common')),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('users/', include('users.urls', namespace='users')),
    path('reservations/', include('reservations.urls', namespace='reservations')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('lists/', include('lists.urls', namespace='lists')),
    path('conversations/', include('conversations.urls', namespace='conversations')),
    path(os.environ.get('ADMIN'), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

reservations/urls.py
from django.urls import path
from . import views


app_name = 'reservations'

urlpatterns = [
    path('create/<int:room>/<int:year>-<int:month>-<int:day>',
         views.create_reservation, name='create'),
    path('<int:pk>', views.ReservationDetailView.as_view(), name='detail'),
    path('<int:pk>/<str:verb>', views.edit_reservation, name='edit'),
    path('list', views.ReservationListView.as_view(), name='list'),
]

rooms/urls.py
from django.urls import path
from . import views


app_name = 'rooms'

urlpatterns = [
    path('<int:pk>', views.RoomDetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.EditRoomView.as_view(), name='edit'),
    path('<int:pk>/photos', views.RoomPhotosView.as_view(), name='photos'),
    path('<int:pk>/photos/add', views.AddPhotoView.as_view(), name='add-photo'),
    path('<int:room_pk>/photos/<int:photo_pk>/delete',
         views.delete_photo, name='delete-photo'),
    path('<int:room_pk>/photos/<int:photo_pk>/edit',
         views.EditPhotoView.as_view(), name='edit-photo'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('create/', views.CreateRoomView.as_view(), name='create'),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('login/github', views.github_login, name='github-login'),
    path('login/github/callback', views.github_callback, name='github-callback'),
    path('login/kakao', views.kakao_login, name='kakao-login'),
    path('login/kakao/callback', views.kakao_callback, name='kakao-callback'),
    path('logout', views.log_out, name='logout'),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('verify/<str:key>', views.complete_verification,
         name='complete-verification'),
    path('update-profile', views.UpdateProfileView.as_view(), name='update'),
    path('update-password', views.UpdatePasswordView.as_view(), name='password'),
    path('<int:pk>', views.UserProfileView.as_view(), name='profile'),
    path('switch-hosting', views.switch_hosting, name='switch-hosting'),
    path('switch-language', views.switch_language, name='switch-language'),
    path('switch-currency', views.switch_currency, name='switch-currency'),
]

templates/partials/footer.html
{% load i18n %}

<footer class='container mx-auto text-center py-3 border-t font-medium text-gray-500'>
    <div class='flex flex-row'>
        <div class='flex-auto text-left mt-2 mb-2'>
            <span>&copy; 2022 Clonebnb, Inc.</span>
            <span class='ml-2'>· <a href="#">{% trans 'Privacy Policy' %}</a></span>
            <span class='ml-2'>· <a href="#">{% trans 'Terms' %}</a></span>
            <span class='ml-2'>· <a href="#">{% trans 'Sitemaps' %}</a></span>
            <span class='ml-2'>· <a href="#">{% trans 'Cancellation Policies' %}</a></span>
            <span class='ml-2'>· <a href="#">{% trans 'Company Details' %}</a></span>
        </div>
        <div class='flex flex-auto text-right mt-2 mb-2'>
            {% get_current_language as LANGUAGE_CODE %}
            <button class='flex underline focus:outline-none' id='locale-btn'>
                <span class="mr-2 mt-1">
                    <svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="presentation" focusable="false" style="display: block; height: 16px; width: 16px; fill: currentcolor;"><path d="m8.002.25a7.77 7.77 0 0 1 7.748 7.776 7.75 7.75 0 0 1 -7.521 7.72l-.246.004a7.75 7.75 0 0 1 -7.73-7.513l-.003-.245a7.75 7.75 0 0 1 7.752-7.742zm1.949 8.5h-3.903c.155 2.897 1.176 5.343 1.886 5.493l.068.007c.68-.002 1.72-2.365 1.932-5.23zm4.255 0h-2.752c-.091 1.96-.53 3.783-1.188 5.076a6.257 6.257 0 0 0 3.905-4.829zm-9.661 0h-2.75a6.257 6.257 0 0 0 3.934 5.075c-.615-1.208-1.036-2.875-1.162-4.686l-.022-.39zm1.188-6.576-.115.046a6.257 6.257 0 0 0 -3.823 5.03h2.75c.085-1.83.471-3.54 1.059-4.81zm2.262-.424c-.702.002-1.784 2.512-1.947 5.5h3.904c-.156-2.903-1.178-5.343-1.892-5.494l-.065-.007zm2.28.432.023.05c.643 1.288 1.069 3.084 1.157 5.018h2.748a6.275 6.275 0 0 0 -3.929-5.068z"></path></svg>
                </span>
                <span class="mr-5">
                    {% if LANGUAGE_CODE == "en" %}
                        {% trans 'English' %} 
                    {% elif LANGUAGE_CODE == "ko" %}
                        {% trans 'Korean' %}
                    {% endif %}
                </span>
            </button>
            <button class='flex underline focus:outline-none' id='currency-btn'>
                <span class="mr-2">
                    {% if request.COOKIES.django_currency == "en" %}
                        $ 
                    {% else %}
                        ₩
                    {% endif %}
                </span>
                <span class="">
                    {% if request.COOKIES.django_currency == "en" %}
                        {% trans 'USD' %}
                    {% else %}
                        {% trans 'KRW' %}
                    {% endif %}
                </span>
            </button>
        </div>
    </div>
</footer>
<div class='fixed hidden inset-0 overflow-y-auto h-full w-full' id='locale-modal'>
    <div class='relative max-w-xl mx-auto my-25vh border w-96 shadow-lg rounded-lg bg-white'>
        <button class='focus:outline-none text-black mt-5 mb-5 ml-5' id='locale-close'><i class="fas fa-times ml-2"></i></button>
        <div class='text-left border-t'>
            <div class='mb-5 mt-5 ml-5 text-2xl text-black font-medium'>{% trans 'Choose a language and region' %}</div>
            <div class='ml-5 mb-5 text-gray-800'>
                <span class="mr-5">
                    <button class='p-2 focus:outline-none rounded-lg hover:bg-gray-200 {% if LANGUAGE_CODE == "en" %} border-gray-600 border {% endif %}' id='eng-btn'>
                        <div class='text-gray-600'>{% trans 'English' %}</div>
                        <div class='text-gray-500'>{% trans 'United States' %}</div>
                    </button>
                </span>
                <span class="mr-5">
                    <button class='p-2 focus:outline-none rounded-lg hover:bg-gray-200 {% if LANGUAGE_CODE == "ko" %} border-gray-600 border {% endif %}' id='kor-btn'>
                        <div class='text-gray-600'>{% trans 'Korean' %}</div>
                        <div class='text-gray-500'>{% trans 'South Korea' %}</div>
                    </button>
                </span>
            </div>
        </div>
    </div>
</div>
<div class='fixed hidden inset-0 overflow-y-auto h-full w-full' id='currency-modal'>
    <div class='relative max-w-xl mx-auto my-25vh border w-96 shadow-lg rounded-lg bg-white'>
        <button class='focus:outline-none text-black mt-5 mb-5 ml-5' id='currency-close'><i class="fas fa-times ml-2"></i></button>
        <div class='text-left border-t'>
            <div class='mb-5 mt-5 ml-5 text-2xl text-black font-medium'>{% trans 'Choose a Currency' %}</div>
            <div class='ml-5 mb-5 text-gray-800'>
                <span class="mr-5">
                    <button class='p-2 focus:outline-none rounded-lg hover:bg-gray-200 {% if request.COOKIES.django_currency == "en" %} border-gray-600 border {% endif %}' id='usd-btn'>
                        <div class='text-gray-600'>{% trans 'United States dollar' %}</div>
                        <div class='text-gray-500'>{% trans 'USD' %} - $</div>
                    </button>
                </span>
                <span class="mr-5">
                    <button class='p-2 focus:outline-none rounded-lg hover:bg-gray-200 {% if request.COOKIES.django_currency == "ko" %} border-gray-600 border {% endif %}' id='krw-btn'>
                        <div class='text-gray-600'>{% trans 'South Korean won' %}</div>
                        <div class='text-gray-500'>{% trans 'KRW' %} - ₩</div>
                    </button>
                </span>
            </div>
        </div>
    </div>
</div>

templates/partials/header.html
<header>
    <a href="{% url 'common:home' %}">clonebnb</a>
    <ul>
        <li><a href="#">Login</a></li>
    </ul>
</header>

templates/partials/messages.html
{% if messages %}
<ul class="absolute top-0 mx-auto left-0 right-0 flex justify-center">
    {% for message in messages %}
    <li class="message font-medium bg-gray-700 z-10 rounded-full text-white py-4 px-6 w-64 text-center {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
{% load i18n %}

<ul class='flex items-center text-sm font-medium h-full'>
        {% if user.is_authenticated %}
            <li class='nav_link'>
                <a href="{% url 'reservations:list' %}">{% trans 'Reservation' %}</a>
            </li>
            <li class='nav_link'>
                <a href="{% url 'users:switch-hosting' %}">
                    {% if request.session.is_hosting %}
                        {% trans 'Stop hosting' %}
                    {% else %}
                        {% trans 'Start hosting' %}
                    {% endif %}
                </a>
            </li>
            {% if request.session.is_hosting %}
                <li class="nav_link"><a href='{% url "rooms:create" %}'>{% trans 'Create Room' %}</a></li>
            {% endif %}
            <li class='nav_link'><a href="{% url 'lists:see-favs' %}">{% trans 'Favourites' %}({{ user.list.rooms.count }})</a></li>
            <li class='nav_link'><a href="{{ user.get_absolute_url }}">{% trans 'Profile' %}</a></li>
            <li class='nav_link'><a href="{% url 'users:logout' %}">{% trans 'Log out' %}</a></li>
        {% else %}
            <li class='nav_link'><a href="{% url 'users:login' %}">{% trans 'Login' %}</a></li>
            <li class='nav_link'><a href="{% url 'users:signup' %}">{% trans 'Sign up' %}</a></li>
        {% endif %}
    </ul>

templates/partials/social_login.html
<div class='flex flex-col w-full'>
    <a href="{% url 'users:github-login' %}" class='btn border-2 border-gray-700 text-gray-700 mb-2'>
        <i class='fab fa-github fa-lg mr-2'></i> Continue with Github
    </a>
    <a href="{% url 'users:kakao-login' %}" class='btn border border-yellow-400 bg-yellow-400 text-yellow-800 mb-2'>
        <i class='fas fa-comment fa-lg mr-2'></i> Continue with Kakao
    </a>
</div>
<div class="flex items-center w-full my-4">
    <div class="h-px w-full bg-gray-400"></div>
    <span class='text-gray-600 font-medium text-sm mx-4'>or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>