lists/urls.py
from django.urls import path
from . import views


app_name = 'lists'

urlpatterns = [
    path('toggle/<int:room_pk>', views.toggle_room, name='toggle-room'),
    path('favs/', views.SeeFavouritesView.as_view(), name='see-favs'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('common.urls', namespace='common')),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('users/', include('users.urls', namespace='users')),
    path('reservations/', include('reservations.urls', namespace='reservations')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('lists/', include('lists.urls', namespace='lists')),
    path('conversations/', include('conversations.urls', namespace='conversations')),
    path(os.environ.get('ADMIN'), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

rooms/urls.py
from django.urls import path
from . import views


app_name = 'rooms'

urlpatterns = [
    path('<int:pk>', views.RoomDetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.EditRoomView.as_view(), name='edit'),
    path('<int:pk>/photos', views.RoomPhotosView.as_view(), name='photos'),
    path('<int:pk>/photos/add', views.AddPhotoView.as_view(), name='add-photo'),
    path('<int:room_pk>/photos/<int:photo_pk>/delete',
         views.delete_photo, name='delete-photo'),
    path('<int:room_pk>/photos/<int:photo_pk>/edit',
         views.EditPhotoView.as_view(), name='edit-photo'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('create/', views.CreateRoomView.as_view(), name='create'),
]

reservations/views.py
import datetime
from django.http import Http404
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.generic import View, ListView
from rooms.models import Room
from reviews.forms import CreateReviewForm
from . import models
import reservations


class CreateError(Exception):
    pass


def create_reservation(request, room, year, month, day):

    if request.user.is_authenticated == False:
        messages.error(request, _("Login required"))
        return redirect(reverse('users:login'))
    try:
        date_obj = datetime.datetime(year=year, month=month, day=day)
        room = Room.objects.get(pk=room)
        models.BetweenDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError()
    except (Room.DoesNotExist, CreateError):
        messages.error(request, _("Can't Reserve That Room"))
        return redirect(reverse('common:home'))
    except models.BetweenDay.DoesNotExist:
        reservation = models.Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),
        )
        return redirect(reverse('reservations:detail', kwargs={'pk': reservation.pk}))


class ReservationDetailView(View):

    def get(self, *args, **kwargs):
        pk = kwargs.get('pk')
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        if not reservation or (
            reservation.guest != self.request.user
            and reservation.room.host != self.request.user
        ):
            raise Http404()
        form = CreateReviewForm()
        return render(
            self.request,
            'reservations/detail.html',
            {
                'reservation': reservation,
                'form': form,
            },
        )


def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if not reservation or (
        reservation.guest != request.user
        and reservation.room.host != request.user
    ):
        raise Http404()
    if verb == 'confirm':
        reservation.status = models.Reservation.STATUS_CONFIRMED
    elif verb == 'cancel':
        reservation.status = models.Reservation.STATUS_CANCELED
        models.BetweenDay.objects.filter(reservation=reservation).delete()
    reservation.save()
    messages.success(request, _('Reservation Updated'))
    return redirect(reverse('reservations:detail', kwargs={'pk': reservation.pk}))


class ReservationListView(ListView):

    template_name = 'reservations/list.html'
    context_object_name = 'reservations'
    ordering = 'created'

    def get_queryset(self):
        try:
            if self.request.session['is_hosting']:
                reservation = models.Reservation.objects.filter(
                    room__host=self.request.user)
            else:
                reservation = models.Reservation.objects.filter(
                    guest=self.request.user)
        except KeyError:
            reservation = models.Reservation.objects.filter(
                guest=self.request.user)
        return reservation

templates/mixins/calendar.html
{% load is_between %}

{% for calendar in room.get_calendars %}
    <div class='mb-20'>
        <span class='text-center font-semibold text-lg block mb-8'>
            {{ calendar.get_month }} / {{ calendar.year }}
        </span>
        <div class='cal-grid font-medium mb-4'>
            {% for day in calendar.day_names %}
                <span>{{ day }}</span>
            {% endfor %}
        </div>
        <div class='cal-grid'>
            {% for day in calendar.get_days %}
                {% is_between room day as is_between_bool %}
                {% if day.number != 0 %}
                    {% if day.past %}
                        <span class="cal-number bg-gray-200 text-gray-400">
                            {{ day }}
                        </span>
                    {% elif is_between_bool %}
                        <span class='cal-number bg-gray-200 text-gray-400 line-through'>
                            {{ day }}
                        </span>
                    {% else %}
                        <a href={% url 'reservations:create' room.pk day.year day.month day.number %} class='cal-number bg-gray-200 text-gray-700 hover:bg-teal-400 hover:text-white hover:font-medium'>
                            {{ day }}
                        </a>
                    {% endif %}
                {% else %}
                    <span></span>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endfor %}

templates/mixins/reservation_card.html
{% load i18n %}

<div class='w-1/4 mb-10 px-3 overflow-hidden'>
    <a href="{% url 'rooms:detail' room.pk %}">
        <div class='w-full h-48 bg-cover bg-center rounded-lg mb-2' style='background-image: url({{ room.first_photo }});'></div>
        <div class='flex justify-between mb-2 truncate'>
            <div class='w-4/5 overflow-hidden flex'>
                {% if room.host.superhost %}
                    <span class='uppercase font-medium text-xs border border-black text-black rounded py-px px-1 mr-2'>
                        {% trans 'superhost' %}
                    </span>
                {% endif %}
                <span class='text-sm text-gray-600 block truncate'>
                    {{ room.city }},
                    {{ room.country.name }}
                </span>
            </div>
            <div class='text-sm flex items-center'>
                <i class="fas fa-star text-red-500 text-xs mr-1"></i>
                {{ room.total_rating }}
            </div>
        </div>
        <span class='text-black w-11/12 block truncate'>
            {{ room.name }}
        </span>
    </a>
    <a href="{% url 'reservations:detail' reservation.pk %}">
        <div class='text-center font-medium mt-3 mb-2'>
            {% trans 'Reservation Info' %}
        </div>
        {% if request.session.is_hosting %}
            <div class='text-center mb-2'>{% blocktrans with guest=reservation.guest.first_name %}Guest : {{ guest }}{% endblocktrans %}</div>
        {% endif %}
        <div class='text-center'>{{ reservation.check_in }} - {{ reservation.check_out }}</div>
        <div class='mt-2 mb-2 text-center'>
            <span class='{% if reservation.status == "pending" %} text-yellow-500 {% elif reservation.status == "canceled" %} text-red-600 {% else %} text-teal-600 {% endif %}'>{{ reservation.get_status_display }}</span>
        </div>
    </a>
</div>

templates/mixins/room_card.html
{% load i18n on_favourites %}

<div class='w-1/4 mb-10 px-2 overflow-hidden'>
    <a href={% url 'rooms:detail' room.pk %}>
        <div class='w-full h-64 bg-cover bg-center rounded-lg mb-2' style='background-image: url({{ room.first_photo }});'></div>
        <div class='flex justify-between mb-2 truncate'>
            <div class='w-4/5 overflow-hidden flex'>
                <span>
                    {% if user.is_authenticated %}
                        {% on_favourites room as on_favs_boolean %}
                        {% if on_favs_boolean %}
                            <a href="{% url 'lists:toggle-room' room.pk %}?action=remove{{ fav }}">
                                <abbr title="{% trans 'Remove from Favourites' %}">
                                    <i class="fa fa-heart mr-3 text-red-600"></i>
                                </abbr>
                            </a>
                        {% else %}
                            <a href="{% url 'lists:toggle-room' room.pk %}?action=add{{ fav }}">
                                <abbr title="{% trans 'Save to Favourites' %}">
                                    <i class="fa fa-heart mr-3 text-gray-300"></i>
                                </abbr>
                            </a>
                        {% endif %}
                    {% endif %}
                </span>
                {% if room.host.superhost %}
                    <span class='uppercase font-medium text-xs border border-black text-black rounded py-px px-1 mr-2'>
                        {% trans 'superhost' %}
                    </span>
                {% endif %}
                <span class='text-sm text-gray-600 block truncate'>
                    {{ room.city }},
                    {{ room.country.name }}
                </span>
            </div>
            <div class='text-sm flex items-center'>
                {% if room.reviews.count %}
                    <i class="fas fa-star text-red-500 text-xs mr-1"></i>
                    {{ room.total_rating }}
                    ({{ room.reviews.count }} reviews)
                {% endif %}
            </div>
        </div>
        <div class='flex justify-between mb-2 truncate'>
            <div class='w-4/5 overflow-hidden flex'>
                <span class='text-black w-11/12 block truncate'>
                    {{ room.name }}
                </span>
            </div>
            <div class='text-sm flex items-center font-bold'>
                {% if request.COOKIES.django_currency == 'ko' %}
                    ₩{{ room.get_krw }}
                {% else %}
                    ${{ room.price }}
                {% endif %}
            </div>
        </div>
    </a>
</div>

templates/mixins/user_avatar.html
{% if user.avatar %}
    <div class='{{ h_and_w|default:"h-20 w-20" }} rounded-full bg-cover' style='background-image: url({{ user.avatar.url }});'>
{% else %}
    <div class='{{ h_and_w|default:"h-20 w-20" }} bg-gray-700 rounded-full text-white flex justify-center items-center overflow-hidden'>
        <span class='{{ text|default:"text-3xl" }}'>{{ user.first_name|first }}</span>
{% endif %}
    </div>