lists/urls.py
from django.urls import path
from . import views


app_name = 'lists'

urlpatterns = [
    path('toggle/<int:room_pk>', views.toggle_room, name='toggle-room'),
    path('favs/', views.SeeFavouritesView.as_view(), name='see-favs'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('common.urls', namespace='common')),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('users/', include('users.urls', namespace='users')),
    path('reservations/', include('reservations.urls', namespace='reservations')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('lists/', include('lists.urls', namespace='lists')),
    path('conversations/', include('conversations.urls', namespace='conversations')),
    path(os.environ.get('ADMIN'), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

rooms/urls.py
from django.urls import path
from . import views


app_name = 'rooms'

urlpatterns = [
    path('<int:pk>', views.RoomDetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.EditRoomView.as_view(), name='edit'),
    path('<int:pk>/photos', views.RoomPhotosView.as_view(), name='photos'),
    path('<int:pk>/photos/add', views.AddPhotoView.as_view(), name='add-photo'),
    path('<int:room_pk>/photos/<int:photo_pk>/delete',
         views.delete_photo, name='delete-photo'),
    path('<int:room_pk>/photos/<int:photo_pk>/edit',
         views.EditPhotoView.as_view(), name='edit-photo'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('create/', views.CreateRoomView.as_view(), name='create'),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django_countries.fields import CountryField
from common.models import AbstractTimeStampedModel
from my_calendar import Calendar


class AbstractItem(AbstractTimeStampedModel):
    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """ RoomType Model Definition """

    class Meta:
        verbose_name = 'Room Type'


class Amenity(AbstractItem):
    """ Amenity Model Definition """

    class Meta:
        verbose_name_plural = 'Amenities'


class Facility(AbstractItem):
    """ Facility Model Definition """

    class Meta:
        verbose_name_plural = 'Facilities'


class HouseRule(AbstractItem):
    """ HouseRule Model Definition """

    class Meta:
        verbose_name = 'House Rule'


class Photo(AbstractTimeStampedModel):
    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to='room_photos')
    room = models.ForeignKey(
        'Room', related_name='photos', on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(AbstractTimeStampedModel):
    """ Room Model Definitions """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", related_name='rooms', on_delete=models.CASCADE)
    room_type = models.ForeignKey(
        "RoomType", related_name='rooms', on_delete=models.SET_NULL, null=True)
    amenities = models.ManyToManyField(
        "Amenity", related_name='rooms', blank=True)
    facilities = models.ManyToManyField(
        "Facility", related_name='rooms', blank=True)
    house_rules = models.ManyToManyField(
        "HouseRule", related_name='rooms', blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = self.city.capitalize()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        if not all_reviews:
            return ''
        all_ratings = 0
        for review in all_reviews:
            all_ratings += review.rating_average()
        return round(all_ratings / len(all_reviews), 2)

    def first_photo(self):
        try:
            photo, = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_calendars(self):
        now = timezone.now()
        this_month = Calendar(now.year, now.month)
        if now.month == 12:
            next_month = Calendar(now.year + 1, 1)
        else:
            next_month = Calendar(now.year, now.month + 1)
        return [this_month, next_month]

    def get_krw(self):
        return int(self.price * 1198.41)

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):
    """ Define SearchForm """

    city = forms.CharField(initial='Seoul', required=False)
    country = CountryField(default='KR').formfield()
    room_type = forms.ModelChoiceField(
        empty_label='Any Kind',
        required=False,
        queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )


class CreatePhotoForm(forms.ModelForm):

    class Meta:
        model = models.Photo
        fields = ('caption', 'file')

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):

    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, user, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.contrib.messages.api import success
from django.http.response import Http404
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import FormView, UpdateView
from django.urls import reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms


class HomeView(ListView):
    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    paginate_orphans = 3
    ordering = 'created'
    context_object_name = 'rooms'
    template_name = 'rooms/home.html'


class RoomDetailView(DetailView):
    """ Room Detail Definition """

    model = models.Room


class SearchView(View):
    """ SearchView Definition """

    def get(self, request):

        country = request.GET.get('country')

        if country:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                city = form.cleaned_data.get('city')
                country = form.cleaned_data.get('country')
                room_type = form.cleaned_data.get('room_type')
                price = form.cleaned_data.get('price')
                guests = form.cleaned_data.get('guests')
                bedrooms = form.cleaned_data.get('bedrooms')
                beds = form.cleaned_data.get('beds')
                baths = form.cleaned_data.get('baths')
                instant_book = form.cleaned_data.get('instant_book')
                superhost = form.cleaned_data.get('superhos')
                amenities = form.cleaned_data.get('amenities')
                facilities = form.cleaned_data.get('facilities')

                filter_args = {}

                if city:
                    filter_args['city__startswith'] = city

                filter_args['country'] = country

                if room_type:
                    filter_args['room_type'] = room_type

                if price:
                    filter_args['price__lte'] = price

                if guests:
                    filter_args['guests__gte'] = guests

                if bedrooms:
                    filter_args['bedrooms__gte'] = guests

                if beds:
                    filter_args['beds__gte'] = guests

                if baths:
                    filter_args['baths__gte'] = guests

                if instant_book:
                    filter_args['instant_book'] = True

                if superhost:
                    filter_args['host__superhost'] = True

                qs = models.Room.objects.filter(
                    **filter_args).order_by('-created')

                for amenity in amenities:
                    qs = qs.filter(amenities=amenity)

                for facility in facilities:
                    qs = qs.filter(facilities=facility)

                page = request.GET.get('page')
                paginator = Paginator(qs, 5, orphans=5)
                rooms = paginator.get_page(page)
                path = request.get_full_path().split(
                    '&page=')[0].replace('/rooms/search/?', '')

                return render(request, "rooms/search.html", context={
                    'form': form, 'rooms': rooms, 'path': path})
        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", context={'form': form})


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    template_name = 'rooms/room_edit.html'
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = 'rooms/room_photos.html'

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        photo = models.Photo.objects.get(pk=photo_pk)
        if room.host.pk != user.pk and user.pk != photo.room.pk:
            messages.error(request, "Can't delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, 'Photo deleted')
        return redirect(reverse('rooms:photos', kwargs={'pk': room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse('common:home'))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = 'rooms/photo_edit.html'
    pk_url_kwarg = 'photo_pk'
    fields = ('caption',)

    def get_success_url(self):
        room_pk = self.kwargs.get('room_pk')
        return reverse('rooms:photos', kwargs={'pk': room_pk})

    def get_object(self, queryset=None):
        photo = super().get_object(queryset=queryset)
        if photo.room.host.pk != self.request.user.pk:
            raise Http404()
        return photo


class AddPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, FormView):

    template_name = 'rooms/photo_create.html'
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        form.save(pk)
        messages.success(self.request, 'Photo Uploaded')
        return redirect(reverse('rooms:photos', kwargs={'pk': pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = 'rooms/room_create.html'

    def form_valid(self, form):
        room = form.save(self.request.user)
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, 'Room Created')
        return redirect(reverse('rooms:detail', kwargs={'pk': room.pk}))

templates/rooms/detail.html
{% extends 'base.html' %}

{% block page_name %}
    {{ room.name }}
{% endblock page_name %}

{% block content %}
    <div>
        <h1>{{ room.name }}</h1>
        <h3>{{ room.description }}</h3>
    </div>
    <div>
        <h2>By: {{room.host.username}}
            {% if room.host.superhost %}
                (superhost)
            {% endif %}
        </h2>
        <h3>Amenities</h3>
        <ul>
            {% for amenity in room.amenities.all %}
                <li>{{ amenity }}</li>
            {% endfor %}
        </ul>
        <h3>Facilities</h3>
        <ul>
            {% for facility in room.facilities.all %}
                <li>{{ facility }}</li>
            {% endfor %}
        </ul>
        <h3>House Rules</h3>
        <ul>
            {% for house_rule in room.house_rules.all %}
                <li>{{ house_rule }}</li>
            {% endfor %}
        </ul>
    </div>

{% endblock content %}

templates/rooms/home.html
{% extends 'base.html' %}

{% load i18n %}

{% block page_title %}
    Home
{% endblock %}

{% block content %}
    <div class="container mx-auto pb-10">
        <div class='rounded-xl bg-gray-800 -mx-40 h-50vh mt-32 mb-24'></div>
        <div class='flex flex-wrap -mx-40 mb-10'>
            {% for room in rooms %}
                {% include 'mixins/room_card.html' with room=room %}
            {% endfor %}
        </div>
        <div class='flex items-center mx-auto container justify-center'>
            {% if page_obj.has_previous %}
                <a href='?page={{ page_obj.previous_page_number }}' class='text-teal-400'>
                    <i class='fas fa-arrow-left fa-lg'></i>
                </a>
            {% endif %}
            <span class='mx-3 font-medium text-lg'>
                {% blocktrans with current_page=page_obj.number total_page=page_obj.paginator.num_pages %}Page {{ current_page }} of {{ total_page }}{% endblocktrans %}
            </span>
            {% if page_obj.has_next %}
                <a href='?page={{ page_obj.next_page_number }}' class='text-teal-400'>
                    <i class='fas fa-arrow-right fa-lg'></i>
                </a>
            {% endif %}
        </div>
        <div class='flex justify-center'>
            {% for page_obj in page_obj.paginator.page_range %}
            <a href='?page={{ page_obj }}'>
                <div class='mx-1'>
                    {{ page_obj }}
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/rooms/photo_create.html
{% extends 'base.html' %}

{% block page_title %}
    Upload photo
{% endblock %}

{% block search_bar %}
{% endblock %}

{% block content %}
    <div class='container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-600'>
        {% include 'mixins/room/room_form.html' with form=form cta='Upload photo' %}
    </div>
{% endblock %}

templates/rooms/photo_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update photo
{% endblock %}

{% block search_bar %}
{% endblock %}

{% block content %}
    <div class='container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-600'>
        {% include 'mixins/room/room_form.html' with form=form cta='Update photo' %}
    </div>
{% endblock %}

templates/rooms/room_create.html
{% extends 'base.html' %}

{% block page_title %}
    Create Room
{% endblock %}

{% block search_bar %}
{% endblock %}

{% block content %}
    <div class='container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-600'>
        {% include 'mixins/room/room_form.html' with form=form cta='Create room' %}
    </div>
{% endblock %}

templates/rooms/room_detail.html
{% extends 'base.html' %}

{% block page_title %}
    {{ room.name }}
{% endblock %}

{% block content %}
    {% include 'mixins/room/room_thumbnail.html' with room=room %}
    <div class='container mx-au flex justify-around pb-56'>
        <div class='w-1/2'>
            {% include 'mixins/room/room_info.html' with room=room %}
            <div class='mt-10'>
                {% include 'mixins/room/room_review.html' with room=room %}
            </div>
        </div>
        <div class='w-1/3'>
            {% if room.host == user %}
                <a href='{% url "rooms:edit" room.pk %}' class='btn-link block'>Edit Room</a>
            {% else %}
                {% if not request.session.is_hosting %}
                    {% include 'mixins/calendar.html' with room=room %}
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/rooms/room_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update Room
{% endblock %}

{% block search_bar %}
{% endblock %}

{% block content %}
    <div class='container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-600'>
        {% include 'mixins/room/room_form.html' with form=form cta='Update room' %}
        <div class="mt-5">
            <a href='{% url "rooms:photos" room.pk %}' class='text-teal-500 font-medium'>Edit Photos</a>
        </div>
    </div>
{% endblock %}

templates/rooms/room_photos.html
{% extends 'base.html' %}

{% block page_title %}
    {{ room.name }}'s Photos
{% endblock %}

{% block search_bar %}
{% endblock %}

{% block content %}
    <div class='container mx-auto my-10 flex flex-col'>
        <div class="my-10 w-full">
            <a href='{% url "rooms:add-photo" room.pk %}' class='btn-link w-1/6 block'>Upload Photo</a>
        </div>
            {% for photo in room.photos.all %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class='flex items-start'>
                    <img src='{{ photo.file.url }}' class='w-32 h-32' />
                    <span class='ml-5 text-xl'>{{ photo.caption }}</span>
                </div>
                <div class='flex flex-col w-1/6'>
                    <a class='btn-link mb-5 bg-teal-400' href='{% url "rooms:edit-photo" room.pk photo.pk %}'>Edit</a>
                    <a class='btn-link bg-red-600' href='{% url "rooms:delete-photo" room.pk photo.pk %}'>Delete</a>
                </div>
            </div>
            {% endfor %}
            <div class="flex justify-center mt-5">
                <a href='{% url "rooms:edit" room.pk %}' class='text-teal-500 font-medium text-xl'>Back to edit room</a>
            </div>
    </div>
{% endblock %}

templates/rooms/search.html
{% extends 'base.html' %}

{% block page_title %}
    Search
{% endblock %}

{% block search_bar %}

{% endblock %}

{% block content %}
    <h2>Search</h2>
    <form method='get' action='{% url "rooms:search" %}'>
        {{ form.as_p }}
        <button>Search</button>
    </form>
    {% if rooms %}
        <h3>Results</h3>
        {% for room in rooms %}
            <h3>{{ room.name }}</h3>
        {% endfor %}
        <h5>
            {% if rooms.has_previous %}
                <a href='?{{ path }}&page={{ rooms.previous_page_number }}'>Previous</a>
            {% endif %}
            Page {{ rooms.number }} of {{ rooms.paginator.num_pages }}
            {% if rooms.has_next %}
                <a href='?{{ path }}&page={{ rooms.next_page_number }}'>Next</a>
            {% endif %}
        </h5>
        {% for page in rooms.paginator.page_range %}
            <a href='?{{ path }}&page={{ page }}'>{{ page }}</a>
        {% endfor %}
    {% endif %}
{% endblock %}