common/urls.py
from django.urls import path
from rooms import views as room_views


app_name = 'common'

urlpatterns = [
    path('', room_views.HomeView.as_view(), name='home'),
]

lists/urls.py
from django.urls import path
from . import views


app_name = 'lists'

urlpatterns = [
    path('toggle/<int:room_pk>', views.toggle_room, name='toggle-room'),
    path('favs/', views.SeeFavouritesView.as_view(), name='see-favs'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('common.urls', namespace='common')),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('users/', include('users.urls', namespace='users')),
    path('reservations/', include('reservations.urls', namespace='reservations')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('lists/', include('lists.urls', namespace='lists')),
    path('conversations/', include('conversations.urls', namespace='conversations')),
    path(os.environ.get('ADMIN'), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

rooms/urls.py
from django.urls import path
from . import views


app_name = 'rooms'

urlpatterns = [
    path('<int:pk>', views.RoomDetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.EditRoomView.as_view(), name='edit'),
    path('<int:pk>/photos', views.RoomPhotosView.as_view(), name='photos'),
    path('<int:pk>/photos/add', views.AddPhotoView.as_view(), name='add-photo'),
    path('<int:room_pk>/photos/<int:photo_pk>/delete',
         views.delete_photo, name='delete-photo'),
    path('<int:room_pk>/photos/<int:photo_pk>/edit',
         views.EditPhotoView.as_view(), name='edit-photo'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('create/', views.CreateRoomView.as_view(), name='create'),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('login/github', views.github_login, name='github-login'),
    path('login/github/callback', views.github_callback, name='github-callback'),
    path('login/kakao', views.kakao_login, name='kakao-login'),
    path('login/kakao/callback', views.kakao_callback, name='kakao-callback'),
    path('logout', views.log_out, name='logout'),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('verify/<str:key>', views.complete_verification,
         name='complete-verification'),
    path('update-profile', views.UpdateProfileView.as_view(), name='update'),
    path('update-password', views.UpdatePasswordView.as_view(), name='password'),
    path('<int:pk>', views.UserProfileView.as_view(), name='profile'),
    path('switch-hosting', views.switch_hosting, name='switch-hosting'),
    path('switch-language', views.switch_language, name='switch-language'),
    path('switch-currency', views.switch_currency, name='switch-currency'),
]

templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet' href='{% static "css/styles.css" %}'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <title>{% block page_title %}{% endblock %}</title>
</head>
<body class='text-gray-800 mt-24 font-light'>
    {% include 'partials/messages.html' %}
    <header class='container max-w-full inset-0 flex items-center justify-between px-6 h-20 border-b border-gray-400 fixed bg-white'>
        <div class='flex items-center w-1/3'>
            <a href='{% url "common:home" %}' class='mr-6'>
                <img class='w-8' src='{% static "img/logo.png" %}' />
            </a>
            {% block search_bar %}
            <form method='get' action='{% url "rooms:search" %}' class='w-9/12'>
                <input 
                    class='search-box border px-5 w-full font-medium text-gray-900 placeholder-gray-600 py-3 rounded-full shadow-md hover:shadow-lg focus:outline-none'
                    name='city' 
                    placeholder="{% trans 'Search by City' %}" 
                />
            </form>
            {% endblock %}
        </div>
        {% include 'partials/nav.html' %}
    </header>

    {% block content %}{% endblock %}

    {% include 'partials/footer.html' %}

    {% include 'load_js.html' %}

</body>
</html>

templates/load_js.html
{% load static %}

<script type="text/javascript">
    const lang_url = "{% url 'users:switch-language' %}";
    const currency_url = "{% url 'users:switch-currency' %}";
</script>
<script src='{% static "javascript/modal.js" %}'></script>